### ISSUE TITLE
WDK?

### ISSUE THREAD

**Issue by andreiw** [Microsoft/Windows-driver-samples#1]
Will the WDK be released as well? What about the IFS kit? (I see the CDFS sample and that includes ntifs.h)

A

**Comment by kfroe** [comment]
There will be a release of the WDK in the near future, to correspond with Windows 10 build 10041 released yesterday.  The IFS kit, which was last used in Vista, has been fully incorporated into the WDK.

**Comment by jmrossy** [comment]
The kits were released to Windows Insiders yesterday. Start [here](https://insider.windows.com/Home/Index "Windows Insiders") and click the "Install the hardware development kits" link.
