### ISSUE TITLE
Vendor name string for 0x096E is wrong

### ISSUE THREAD

**Issue by Geoffrey-Li** [Microsoft/Windows-driver-samples#101]
In file https://github.com/Microsoft/Windows-driver-samples/blob/master/usb/usbview/vndrlist.h, there is a vendor list for USB devices, but the name for 0x096E item is wrong, it should be "Feitian Technologies Co., Ltd." From http://www.the-sz.com/products/usbid/index.php?v=096E&p=&n= , you can see the Manufacture website is www.ftsafe.com, so you can find the name from that website.

**Comment by MichelleBergeron** [comment]
Thanks - we're tracking this on our end and we'll fix it in a future version.

- Michelle B. @ Windows USB team

**Comment by wm1** [comment]
The data comes from USB Implementers Forum (usb.org) directly. Microsoft does not maintain a separated list.

The real solution is for the vendor to contact usb.org and have their registered name updated. Microsoft will then pull the vendor list from there.

**Comment by Geoffrey-Li** [comment]
I can not get this information directly from usb.org, but from http://www.linux-usb.org/usb.ids our company is named "Feitian Technologies, Inc.". I think this is ok for us, "Feitian **New** Technology Co."  in https://github.com/Microsoft/Windows-driver-samples/blob/master/usb/usbview/vndrlist.h is totally wrong.

**Comment by wm1** [comment]
The USB Implementers Forum is the authority which assigns and maintains all USB Vendor ID Numbers. Check out "Getting a Vendor ID" page at http://www.usb.org/developers/vendor/ for start. Further inquiry on how to update usb.org's records on company name should also be directed to usb.org as well.

**Comment by Geoffrey-Li** [comment]
I have sent email to admin@usb.org, hope get the response ASAP.
Thank you very much.

**Comment by Geoffrey-Li** [comment]
usb.org has corrected our company name, please update the list.

**Comment by wm1** [comment]
The list is not updated on their website yet. I'll check it again in one month. You can ping me here if I forget to do so.

**Comment by Geoffrey-Li** [comment]
I have got response from usb.org, they update this list quarterly, last time is March 2, so  the list maybe will be updated next time at June 2017.

**Comment by Geoffrey-Li** [comment]
@wm1 ,
Would you please help to check whether usb.org has updated the corresponding company name to 0x096E now?

**Comment by wm1** [comment]
vndrlist.h is updated. Please check.

**Comment by Geoffrey-Li** [comment]
thank you very much.
