### ISSUE TITLE
Missing wsksmple.tmh in echosrv project

### ISSUE THREAD

**Issue by xiaoyinl** [Microsoft/Windows-driver-samples#102]
On `network/wsk/echosrv/wsksmple.c` [Line 53](https://github.com/Microsoft/Windows-driver-samples/blob/master/network/wsk/echosrv/wsksmple.c#L53), it includes "`wsksmple.tmh`", but this file doesn't exist in the project directory. This causes some variables undefined, such as `TRCINFO`, `TRCERROR`.

**Comment by wm1** [comment]
tmh file is auto generated during build. You should be able to find `wsksmple.tmh` under x64\debug folder after running msbuild successfully. Refer to https://msdn.microsoft.com/en-us/windows/hardware/drivers/devtest/wpp-preprocessor for more details.
