### ISSUE TITLE
Visual Studio 2022 with WDK and the WDK templates installed

### ISSUE THREAD

**Issue by bundgaard** [microsoft/Windows-driver-samples#1030]
Hi, 
I do not really know where to put this issue, but following the [download-the-wdk](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) guide for Visual Studio 2022 and when asked to download the VSIX with the Visual Studio templates, they seem to be broken.

The UMDF V2 sample includes `#include <device.tmh>` which seems to be a typo.
Also, it doesn't compile as the `TRACE_DEVICE`, `TRACE_LEVEL_ERROR`, and `WDF_POINTER_TYPE_DEVICE_CONTEXT DeviceGetContext(...)` has errors.

Is it something the team for this project can take and push forward or answer back with a way to contact you guys to get this fixed?

Many thanks for considering my request.

**Comment by FrankHan1652** [comment]
Having the same issue. Followed the suggestions in [https://stackoverflow.com/questions/42872409/cannot-compile-visual-studios-template-for-umdf-usb-drivers] but nothing went better;

**Comment by lapaz17** [comment]
Did you find solution?

**Comment by 11philip22** [comment]
I have the same issue. Plz fix, Microsoft

**Comment by daiplusplus** [comment]
Go to your **Project Properties > Wpp Tracing > Run Wpp Tracing** - set it to "Yes" and the solution should build fine.

The "missing" `device.tmh` file is actually generated by the build itself.

**Comment by epmpub** [comment]
> Go to your **Project Properties > Wpp Tracing > Run Wpp Tracing** - set it to "Yes" and the solution should build fine.
> 
> The "missing" `device.tmh` file is actually generated by the build itself.

 i can't find the option..... 

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.10.0

**Comment by daiplusplus** [comment]
@epmpub 

It should look like this:

![image](https://github.com/microsoft/Windows-driver-samples/assets/1693078/6ea4323f-d6fd-4d63-9a46-02e502e39799)

-----

Note that these extra VC Project Properties pages don't appear until-and-unless you have the Windows DDK installed _and_ your `.vcxproj` is a driver (KMDF/UMDF_ project. It needs special imports etc.

**Comment by Sqrtx2** [comment]
> @epmpub
> 
> It should look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1693078/338452278-6ea4323f-d6fd-4d63-9a46-02e502e39799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDk4NTksIm5iZiI6MTcyMzEwOTU1OSwicGF0aCI6Ii8xNjkzMDc4LzMzODQ1MjI3OC02ZWE0MzIzZi1kNmZkLTRkNjMtOWE0Ni0wMmU1MDJlMzk3OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDkzMjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThmNjI0Njg0MTI4N2ZhZDFlOWFhOGQxNWYwM2U2ZWZiMGU2OWMxNDIwZjhiMWYzN2I3YmUxNjZlYjdjMzVlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vB5GmHzwUHX17Uxyyebox8CRbKLBRB8YeP0BQiNM16g)
> 
> Note that these extra VC Project Properties pages don't appear until-and-unless you have the Windows DDK installed _and_ your `.vcxproj` is a driver (KMDF/UMDF_ project. It needs special imports etc.

I have this setting enabled but I still have the same issue, what could be other potential fixes?

**Comment by daiplusplus** [comment]
@Sqrtx2  What is the actual build output you get?

**Comment by Sqrtx2** [comment]
> @Sqrtx2 What is the actual build output you get?
@daiplusplus 

I have already managed to fix my issue (forgot to edit my reply, sorry). I fixed it by installing a few older versions of spectre mitigations.

**Comment by HydraDragonAntivirus** [comment]
It didn't show me VC Project Properties pages even if it's KMDF project.

**Comment by shobhitvaish** [comment]
> It didn't show me VC Project Properties pages even if it's KMDF project. Edit: Install this https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (Latest) MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (Latest) C++ ATL for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) C++ ATL for latest v143 build tools with Spectre Mitigations (x86 & x64) C++ MFC for latest v143 build tools with Spectre Mitigations (ARM64/ARM64EC) C++ MFC for latest v143 build tools with Spectre Mitigations (x86 & x64) Edit: Still didn't work. Edit: https://www.youtube.com/watch?v=n463QJ4cjsU Watch this and do all steps.

I saw the video. The guy doesn't have this option either.
