### ISSUE TITLE
[audio/sysvad] Missing of TabletAudioSample.inf file in SysVad Debug folder

### ISSUE THREAD

**Issue by 7702865800** [microsoft/Windows-driver-samples#1148]
In the debug folder I didn't get the TabletAudioSample.inf file Can you help me with this?

**Comment by judzmura** [comment]
Hello, the tabletAudioSample.inf has been removed from the Sysvad sample driver because it was monolithic and no longer compatible. Now you should only use the componentized sample that is built with Sysvad.
