### ISSUE TITLE
sysvad solution is missing package.vcxproj

### ISSUE THREAD

**Issue by MBulli** [Microsoft/Windows-driver-samples#117]
I tried to follow the steps in the readme for [automatic deployment](https://github.com/Microsoft/Windows-driver-samples/tree/master/audio/sysvad#automatic-deployment) of the sysvad driver sample.

After successfully building the solution and configuring the target computer the next step is to actually deploy the driver but I wasn't able to configure the deployment of the driver because in my solution the package project fails to load. VS fails to find the project file. Actually I couldn't find it anywhere. Because of that I was unable to follow the steps in the readme.

After I pulled the latest changes the package folder was gone. 
It was removed from the solution file in 5d4e0d88ceba97ec2f6f5751b8ff10917f173459.
I also noticed that the package.vcxproj file was deleted in 96eb96dfb613e4c745db6bd1f53a92fe7e2290fc.

As I'm new to the WDK I don't know how to proceed.
If the recommended way of deploying the test driver has changed the readme should reflect these changes.

**Comment by girishpattabiraman** [comment]
Added Package project in new pull request. This should compile the INF files into architecture specific INF.
