### ISSUE TITLE
Inconsistency between official MS driver development documentation and these examples (biometric)

### ISSUE THREAD

**Issue by shimaowo** [microsoft/Windows-driver-samples#1181]
The biometric driver sample was removed in February in #1111 (related to #828), apparently for being outdated. However, [the Microsoft guide for writing a biometric driver](https://learn.microsoft.com/en-us/windows-hardware/drivers/biometric/), which claims to be recent as of last March, references this sample many times.

I submitted feedback on that page, but I assume it won't be seen. I'm not really sure how or where to report these inconsistencies where teams clearly didn't communicate, but this makes developing such a driver a bit unpleasant when the samples claim the documented method is obsolete, but also don't provide any alternatives.

**Comment by tedhudek** [comment]
Hi @shimaowo, thank you for the feedback. Please see the Note that we just added to https://learn.microsoft.com/en-us/windows-hardware/drivers/biometric/sample-biometric-driver.
