### ISSUE TITLE
[serial/serial] Fail to run HLK test for Serial device driver

### ISSUE THREAD

**Issue by longnhieu7** [microsoft/Windows-driver-samples#1206]
I am getting in trouble with HLK testing on New Windows11 24H2 about DRIVER_ISOLATION_VIOLATION. I want to create PortName to Registry 'HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM’ in pnp.c (My program same as Window driver example on Github for W11 22H2) I caught errors "Registry operations should not use absolute paths. Detected creation of unisolated registry key..." and "Registry operations should only use key handles returned from WDF or WDM APIs. Detected creation of unisolated registry key...".
My INF DIRIDS value is 12, is this point make my driver cannot set value into registry?

**Comment by longnhieu7** [comment]
Mr @zlockard told me to test on HLK version 22H2 so I could pass this test. But I would like to make sure that the problem does not come from DIRIDS value and the API we used to set value of COM port. Thank everyone for support!!!

**Comment by zlockard** [comment]
Using DIRD 13 is always recommended and won't cause any issues here
