### ISSUE TITLE
network/modem/fakemodem Fails to build; INX errors from Infverify step

### ISSUE THREAD

**Issue by hholtmann1970** [Microsoft/Windows-driver-samples#133]
All tool pre-requisites installed; VS2015 Pro with Win10 DDK/SDK, etc

Building fakemodem fails in both VS2015 Pro (update 3) and using MSBUILD command line build script provided in the root of the DDK examples.

Severity	Code	Description	Project	File	Line	Suppression State
Error	1209	Section [sourcedisksfiles] is defined multiple times.	fakemodem	C:\proj\github\Windows-driver-samples\network\modem\fakemodem\mdmfake.inx	96	
Error	1209	Section [destinationdirs] is defined multiple times.	fakemodem	C:\proj\github\Windows-driver-samples\network\modem\fakemodem\mdmfake.inx	109	

I can't believe MICROSOFT does NOT at least Build Test their shit before they upload it!!!!
Build, Test, FIX, FIX, FIX.. THEN COMMIT!

-- here is the fix
;HH: fix error 1209; duplciate sections; commenting out the ModemX coinstaller section
;	Since Coinstallers are NOT supported by UWD
;
;--- ModemX Coinstaller installation ------
;
;[DestinationDirs]
;ModemX_CoInstaller_CopyFiles = 11
;
;[ModemX.NT.CoInstallers]
;AddReg=ModemX_CoInstaller_AddReg
;CopyFiles=ModemX_CoInstaller_CopyFiles
;
;[ModemX_CoInstaller_AddReg]
;HKR,,CoInstallers32,0x00010000, "WdfCoInstaller$KMDFCOINSTALLERVERSION$.dll,WdfCoInstaller"
;
;[ModemX_CoInstaller_CopyFiles]
;WdfCoInstaller$KMDFCOINSTALLERVERSION$.dll
;
;;[SourceDisksFiles]
;;WdfCoInstaller$KMDFCOINSTALLERVERSION$.dll=99 ; make sure the number matches with SourceDisksNames
;
;[ModemX.NT.Wdf]
;KmdfService = fakemdm, fakemdm_wdfsect
;[fakemdm_wdfsect]
;KmdfLibraryVersion = $KMDFVERSION$

**Comment by wm1** [comment]
Fixed in bf93ae3e9d74d8863e23e10482da04d01c9fa947
