### ISSUE TITLE
about minifilter IRP_SETINFORMATION ProtectFiles

### ISSUE THREAD

**Issue by MaMyYyY** [Microsoft/Windows-driver-samples#157]
minifilter-->FileDispositionInformation  

can not protect files

shift+delete can delete files, so how can i stop this?

**Comment by rodwiddowson** [comment]
**[FILE_DELETE_ON_CLOSE](https://msdn.microsoft.com/en-us/library/bb432380(v=vs.85).aspx )**


 _Delete the file when the last handle to it is passed to NtClose. If this flag is set, the DELETE flag must be set in the DesiredAccess parameter._

.... And there are better places to be getting free support than here.  A lot of people start [here](http://www.osronline.com/showlists.cfm?list=ntfsd)

**Comment by MaMyYyY** [comment]
thanks ,  it`s work fine
