### ISSUE TITLE
USBView doesn't build because of usbschema.hpp

### ISSUE THREAD

**Issue by Tails86** [Microsoft/Windows-driver-samples#16]
I can't get USBView to build because there are missing definitions within usbschema.hpp. For instance,  deviceIsOperatingAtSuperSpeedPlusOrHigher variable is not defined and UsbBillboardCapabilityDescriptorType class is not defined. When I try to run "xsd.exe /language:CPP /c /order /namespace:Microsoft.Kits.Samples.Usb" the xsd application just spits out options list. What do I need to do to get this to compile?

**Comment by Tails86** [comment]
It seems like I'm missing the xsd schema file in order to regenerate usbschema.hpp file myself.

**Comment by DavidEGrayson** [comment]
I just got usbview to build in MSYS2, and added a package for it: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-usbview

I had some of the same problems you had, and I solved them by building an older version of usbview that can be found here:

https://code.msdn.microsoft.com/windowshardware/USBView-sample-application-e3241039/file/51333/38/USBView%20sample%20application.zip

**Comment by barrygolden** [comment]
Updated usbschema.hpp to fix compile error.
