### ISSUE TITLE
Under certain conditions it's a forever loop., Needs to be replaced with a break; or ...

### ISSUE THREAD

**Issue by indrekmgi** [Microsoft/Windows-driver-samples#183]
https://github.com/Microsoft/Windows-driver-samples/blob/2cbdf8a4423e8c1c72e049740d940b627e2ad29f/usb/usbview/display.c#L4928

**Comment by wm1** [comment]
Fixed in commit 0990b0cbbd460336036dc6ec71cb8e2a8403e287
