### ISSUE TITLE
Devcon utility OneCore Compliant?

### ISSUE THREAD

**Issue by anupdw** [microsoft/Windows-driver-samples#189]
Devcon.exe works only on windows desktop. Any plans to port this to Universal Windows app? Make it OneCore compliant? Should work on windows 10 IOT Core.
Found a way to port SetupAPI to make it OneCore compliant.
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/porting-from-setupapi-to-cfgmgr32

**Comment by jasonknichel** [comment]
Devcon was meant as a sample to demonstrate how to use various SetupApi APIs.  There is no plan to make it OneCore compliant.  Most of its functionality is supported in the inbox utility pnputil.exe.  Please see https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon-migration
