### ISSUE TITLE
几年了，这个问题还存在。

### ISSUE THREAD

**Issue by kouzhudong** [Microsoft/Windows-driver-samples#192]
Windows-driver-samples\trunk\filesys\miniFilter\simrep\simrep.c
有如下两行信息：
buffer = ExAllocatePoolWithTag( PagedPool, SIMREP_STRING_TAG, bufferLength );
buffer = ExAllocatePoolWithTag( PagedPool, SIMREP_STRING_TAG, bufferLength );
看懂了吧！第二个和第三个参数写反了，好几个WDK的版本都存在这个问题。

http://correy.webs.com

**Comment by wm1** [comment]
Thanks for reporting. Fix it now. The build process did not detect the issue unfortunately ...
