### ISSUE TITLE
Request: source code for inf2cat and signtool

### ISSUE THREAD

**Issue by DavidEGrayson** [Microsoft/Windows-driver-samples#20]
Since [inf2cat](https://msdn.microsoft.com/en-us/library/windows/hardware/ff547089%28v=vs.85%29.aspx) and [signtool](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551778%28v=vs.85%29.aspx) are important tools used to make drivers, I think the Windows driver community would benefit from seeing how they work and being able to modify them.  I request that you add the source code of those two utilities to this repository.  (Or if the source code is available somewhere else, please let me know.  I could not find it.)  Thanks!

**Comment by wm1** [comment]
Other tool like devcon is useful because IHV might need to write their own setup utility; but I cannot think of any user case when IHV need to write another signtool.

**Comment by DavidEGrayson** [comment]
I can think of a big reason to make signtool open source.  The "signtool verify" feature is supposed to check whether your signature is good, but there are many cases where "signtool verify" shows no errors and yet developers still run into problems when trying to use the signed files (e.g. Code 52 when loading a driver).  I'm helping someone over email right who is in that situation.  I wrote this [big article](http://www.davidegrayson.com/signing) with the [requirements](http://www.davidegrayson.com/signing/#reqs) for a successful signature and I think signtool doesn't check most of those requirements.  I know Vista is almost dead, but "signtool" never warned about how kernel modules have to be signed with SHA-1 to work in Windows Vista.  I have not tested this recently but I don't think it provides any warnings against using SHA-1 now that it is being phased out.
