### ISSUE TITLE
What happen if custom sAPOs introduce 50ms latency in audio processing chain?

### ISSUE THREAD

**Issue by wanzhang** [Microsoft/Windows-driver-samples#23]
In MSDN document, it says that:

     GFX sAPOs should avoid introducing more than 10 ms of latency into the audio processing chain.

What happen if a custom sAPO introduces around 50ms of latency?

**Comment by mvaneerde** [comment]
Then all audio that goes through it will be delayed by 50 ms... this is bad for things like Voice over IP, for example.
Report the delay you are adding in IAudioProcessingObject::GetLatency

**Comment by wanzhang** [comment]
Thanks for reply.
