### ISSUE TITLE
Remote installation of sysvad_tabletaudiosample makes target hang

### ISSUE THREAD

**Issue by alfredo-ossic** [Microsoft/Windows-driver-samples#25]
After following the recommendations on the reported issues, when trying to deploy the drivers using visual studio the target system hangs.

Target: Windows 10 x86
Used Visual studio 2015

**Comment by mvaneerde** [comment]
Does the mouse move on the target system?

Can you trigger a crash dump with NotMyFault and share it? https://technet.microsoft.com/en-us/sysinternals/bb963901.aspx

**Comment by alfredo-ossic** [comment]
Hi Matthew,

I am currently traveling, but as soon as I can I’ll send you the crash dump. 

Thanks for the help.
Alfredo
