### ISSUE TITLE
Manual install of sysvad_tabletaudiosample fails

### ISSUE THREAD

**Issue by alfredo-ossic** [Microsoft/Windows-driver-samples#26]
Target: Windows 10 x86

These are the logs from setupapi.dev.log

[Device Install Log]
     OS Version = 10.0.10240
     Service Pack = 0.0
     Suite = 0x0100
     ProductType = 1
     Architecture = x86

[BeginLog]

[Boot Session: 2015/10/15 13:49:43.345]

> > >  [Device Install (DiInstallDevice) - ROOT\MEDIA\0000]
> > >  Section start 2015/10/15 14:06:53.006
> > >       cmd: "C:\Windows\system32\mmc.exe" C:\Windows\system32\devmgmt.msc
> > >      dvi: Selected driver installs from section [SYSVAD_SA] in 'c:\users\wdkremoteuser\desktop\debug\package\tabletaudiosample.inf'.
> > >      dvi: Class GUID of device remains: {4d36e96c-e325-11ce-bfc1-08002be10318}.
> > >      dvi: Set selected driver complete.
> > >      ndv: Driver package 'c:\users\wdkremoteuser\desktop\debug\package\tabletaudiosample.inf' exists under 
> > >                          'C:\Windows\System32\DriverStore\FileRepository\tabletaudiosample.inf_x86_fe8ba9a060f09a3c\tabletaudiosample.inf' (oem20.inf).
> > >      inf: Opened PNF: 'C:\Windows\System32\DriverStore\FileRepository\tabletaudiosample.inf_x86_fe8ba9a060f09a3c\tabletaudiosample.inf' ([???])
> > > <<<  Section end 2015/10/15 14:06:53.027
> > > <<<  [Exit status: FAILURE(0xe0000203)]
> > > 
> > >  [Device Install (DiInstallDevice) - ROOT\MEDIA\0000]
> > >  Section start 2015/10/15 14:06:53.030
> > >       cmd: "C:\Windows\system32\mmc.exe" C:\Windows\system32\devmgmt.msc
> > >      dvi: {Plug and Play Service: Device Install for ROOT\MEDIA\0000}
> > >      ump:      Creating Install Process: DrvInst.exe 14:06:53.061
> > > !    ndv:      Installing NULL driver!
> > >      dvi:      Set selected driver complete.
> > >      dvi:      {DIF_ALLOW_INSTALL} 14:06:53.068
> > >      dvi:           Using exported function 'MediaClassInstaller' in module 'C:\Windows\system32\mmci.dll'.
> > >      dvi:           Class installer == mmci.dll,MediaClassInstaller
> > >      dvi:           No CoInstallers found
> > >      dvi:           Class installer: Enter 14:06:53.074
> > >      dvi:           Class installer: Exit
> > >      dvi:           Default installer: Enter 14:06:53.076
> > >      dvi:           Default installer: Exit
> > >      dvi:      {DIF_ALLOW_INSTALL - exit(0xe000020e)} 14:06:53.077
> > >      dvi:      {DIF_REGISTER_COINSTALLERS} 14:06:53.078
> > >      dvi:           Class installer: Enter 14:06:53.079
> > >      dvi:           Class installer: Exit
> > >      dvi:           Default installer: Enter 14:06:53.080
> > >      dvi:                Co-installers registered.
> > >      dvi:           Default installer: Exit
> > >      dvi:      {DIF_REGISTER_COINSTALLERS - exit(0x00000000)} 14:06:53.082
> > >      dvi:      {DIF_INSTALLDEVICE} 14:06:53.083
> > >      dvi:           No CoInstallers found
> > >      dvi:           Class installer: Enter 14:06:53.085
> > >      dvi:           Class installer: Exit
> > >      dvi:           Default installer: Enter 14:06:53.086
> > > !    dvi:                Installing NULL driver!
> > >      dvi:                Install Null Driver: Removing device sub-tree. 14:06:53.088
> > >      dvi:                Install Null Driver: Removing device sub-tree completed. 14:06:53.092
> > >      dvi:                Install Null Driver: Restarting device. 14:06:53.096
> > >      dvi:                Install Null Driver: Restarting device completed. 14:06:53.097
> > >      dvi:                Writing common driver property settings.
> > >      dvi:                Install Device: Configuring device class. 14:06:53.100
> > >      dvi:                Install Device: Configuring device class completed. 14:06:53.101
> > >      dvi:                Install Device: Starting device. 14:06:53.102
> > >      dvi:                Install Device: Starting device completed. 14:06:53.105
> > >      dvi:           Default installer: Exit
> > >      dvi:      {DIF_INSTALLDEVICE - exit(0x00000000)} 14:06:53.111
> > >      dvi:      {DIF_DESTROYPRIVATEDATA} 14:06:53.114
> > >      dvi:           Class installer: Enter 14:06:53.194
> > >      dvi:           Class installer: Exit
> > >      dvi:           Default installer: Enter 14:06:53.200
> > >      dvi:           Default installer: Exit
> > >      dvi:      {DIF_DESTROYPRIVATEDATA - exit(0xe000020e)} 14:06:53.202
> > >      ump:      Server install process exited with code 0x00000000 14:06:53.205
> > >      ump: {Plug and Play Service: Device Install exit(00000000)}
> > > <<<  Section end 2015/10/15 14:06:53.210
> > > <<<  [Exit status: SUCCESS]

**Comment by mvaneerde** [comment]
Please pick up this change and retry: https://github.com/Microsoft/Windows-driver-samples/commit/2c9b5b696dc2c396e6ffc9ec721d8085f279a114
