### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by bluefoxicy** [Microsoft/Windows-driver-samples#286]
There is no LICENSE file for this repository.  Is it MIT licensed or something else?

**Comment by upiter** [comment]
It's already here since https://github.com/Microsoft/Windows-driver-samples/commit/fb242817317ff9b144fad28f4e3884207d101e35: [Microsoft Public License](https://github.com/Microsoft/Windows-driver-samples/blob/master/LICENSE)
