### ISSUE TITLE
Sample for Bluetooth Low Energy? 

### ISSUE THREAD

**Issue by westside** [microsoft/Windows-driver-samples#359]
Thank you in advance. 
I want to write a driver for bluetooth low energy device, but could not find any sample. 
Is there sample for Bluetooth Low Energy? 

I am using custom service and characteristic on BLE.

**Comment by lsgxxlyt** [comment]
HI：
    you can download and see this packet, http://www.wch.cn/downloads/CH579EVT_ZIP.html, 




At 2019-03-19 20:13:20, "Sangwon Choi" <notifications@github.com> wrote:


Thank you in advance.
I want to write a driver for bluetooth low energy device, but could not find any sample.
Is there sample for Bluetooth Low Energy?
