### ISSUE TITLE
Is there any guideline to transfer audio samples from virtual sound card to real one?

### ISSUE THREAD

**Issue by wanzhang** [microsoft/Windows-driver-samples#36]
I‘m considering to develop a virtual sound card driver, which could capture all audio data. But at the same time, the audio data need to play in a real sound card driver. The question is how could I transfer audio samples from my virtual sound card to real sound card?  Is it possible to finish it in Windows 10 and what  documents should I read?

**Comment by wanzhang** [comment]
I find Audio Repeater could do my job, but I do really want to know what technology behind it.

**Comment by Adonis-Song** [comment]
@wanzhang Hi. I met same question. Do you have any ideas?

**Comment by v-junyli** [comment]
We are closing out this issue that unfortunately have not been addressed for a long time.  If you have data that issue remains, then feel free to reactivate.
