### ISSUE TITLE
After compiling Windows Filtering Platform Sample in VS 2015 the WFPSampler.exe won't run on any Windows

### ISSUE THREAD

**Issue by biancazzurri** [microsoft/Windows-driver-samples#37]
The error in event logger is:
Code Integrity determined that the page hashes of an image file are not valid. The file could be improperly signed without page hashes or corrupt due to unauthorized modification. The invalid hashes could indicate a potential disk device error.

**Comment by v-junyli** [comment]
We are closing out this issue that unfortunately have not been addressed for a long time.  If you have data that issue remains, then feel free to reactivate.
