### ISSUE TITLE
Unable to tell what bit-architecture of Devcon that I'm using.

### ISSUE THREAD

**Issue by dretta** [microsoft/Windows-driver-samples#382]
So at work our computers comes with devcon pre-installed but nothing else from the WDK that I'm aware of. I'm trying to make use of it with a USB-connected device but it seems that all of the commands are failing for it. [I've found an answer on SO mentioning that I might be using the wrong version](https://stackoverflow.com/a/40942435/2361174) which makes sense since it's a common issue around here. The problem is I have no way of confirming this, because nowhere I've looked tells me anything about which bit-architecture I'm using.

I understand that I might be digging down the wrong rabbit hole here, but shouldn't there be easy way of telling what version I'm using? I.e. Put in a version option for the command?

**Comment by jasonknichel** [comment]
It is recommended that you use the inbox pnputil.exe instead of devcon.  pnputil supports most of the functionality that devcon does.  Please see https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon-migration
