### ISSUE TITLE
KMDOD sample removed?

### ISSUE THREAD

**Issue by tdicola** [Microsoft/Windows-driver-samples#4]
I noticed the video/KMDOD (kernel-mode display-only driver) sample isn't available for some reason.  You can see a google cached version of it here: http://webcache.googleusercontent.com/search?q=cache:ufhMvxa060cJ:https://github.com/Microsoft/Windows-driver-samples/tree/master/video/KMDOD+&cd=1&hl=en&ct=clnk&gl=us  Is there any particular reason this driver was removed, and can it be re-added?

**Comment by jmrossy** [comment]
You're correct, this sample was temporarily removed as some updates are made to it. We do intend to add it back. Thanks!
