### ISSUE TITLE
Weird IOCTL define

### ISSUE THREAD

**Issue by chm-tm** [Microsoft/Windows-driver-samples#40]
The define for the OSRUSBFX2 IOCTL found in the usb samples:
`#define FILE_DEVICE_OSRUSBFX2   0x65500`
doesn't make sense. Only the lower 16bit will be taken into account, which will effectively land in the Microsoft reserved IOCTL space.
It's quite obvious that the intent was this one:
`#define FILE_DEVICE_OSRUSBFX2   65500`
or
`#define FILE_DEVICE_OSRUSBFX2   0xffdc`

**Comment by MichelleBergeron** [comment]
This has been fixed
