### ISSUE TITLE
DUMB QUESTION -- HD AUDIO DEVICE

### ISSUE THREAD

**Issue by DaveFash** [Microsoft/Windows-driver-samples#47]
I accidentally removed my HD Audio Device from my Windows 10 system (via Control Panel).
I tried reinstalling my Audio Drivers -- but the error said it could not find an Audio Device.
H E L P
I am out of business with recording!!!
If you can possibly give me some things to try...
I will very much appreciate it.

**Comment by wm1** [comment]
Not a coding issue.
