### ISSUE TITLE
inx file in samples

### ISSUE THREAD

**Issue by AtomuHidaka** [Microsoft/Windows-driver-samples#5]
Some of inx file in samples doesn't have CR/LF line end. Stampinf doesn't treat this correctly. It will make build-error for the sample projects.
Please fix these inx files.

**Comment by jmrossy** [comment]
Hi Atomu, thanks for pointing this out.
Can you specify for which samples this causes build breaks?

**Comment by AtomuHidaka** [comment]
Hi,
storage/ramdisk
general/echo

**Comment by IrinVoso** [comment]
0b386da should address this by forcing .inx files to have crlf on checkout.
