### ISSUE TITLE
Cannot build solution in VS2015

### ISSUE THREAD

**Issue by electroncian** [Microsoft/Windows-driver-samples#55]
Hi,

I got the following "Cannot specify [ClassInstall32] section for Microsoft-defined class.   WudfBioUsbSample    C:\Users\aniv\Desktop\Windows-driver-samples-master\biometrics\driver\WudfBioUsbSample.inx  22" error during build this solution in VS2015 and WDK 10.

Best Regards,
Andriy.

**Comment by efalk** [comment]
I think you're supposed to just delete it. See https://social.msdn.microsoft.com/Forums/en-US/24f7babd-8fb9-410a-8fd6-7d16b0abb508/wudfbiousbsampleinx2222-error-1285-cannot-specify-classinstall32-section-for?forum=wdk

**Comment by wm1** [comment]
The ClassInstall32 section has been deleted from WDK version 1607
