### ISSUE TITLE
Failure loading SimpleAudioSample driver - driver entry point not found (Code 39)

### ISSUE THREAD

**Issue by belargo** [microsoft/Windows-driver-samples#592]
**SimpleAudioSample** driver has been built with the latest version of VisualStudio 2019 (16.9.2) **for** x64 platform.
Installing driver with devcon on target machine doesn't produce any errors.
Checking installed driver status in Device Manager reveals that the driver was not loaded.
Device status:
"Windows cannot load the device driver for this hardware. The driver may be corrupted or missing (Code 39)

{Driver Entry Point Not Found}
...
See attached screenshot.
![Screenshot 2021-03-18 200726](https://user-images.githubusercontent.com/50957335/111715513-5b7f3780-882a-11eb-8512-4b6d44439a84.png)

**Comment by belargo** [comment]
The problem mysteriously disappeared after most recent Windows update on March 29, 2021.

**Comment by Thomsywj** [comment]
Please, How can I solved the issue？thx

**Comment by Thomsywj** [comment]
Please，are there some updates？

**Comment by IM-Boting** [comment]
> Please，are there some updates？

update to 2004 or higher. Versions above 2004 can be used normally. But I want to know how to be compatible with the lower version。

**Comment by AndreiHarasemiuc** [comment]
Having this exact problem too and I'm on the most recent Windows 10 version, well beyond 2004.

Any help please?

**Comment by AndreiHarasemiuc** [comment]
Can you reopen this @belargo ?
