### ISSUE TITLE
license for contributions

### ISSUE THREAD

**Issue by jlovejoy** [Microsoft/Windows-driver-samples#60]
Can you please clarify or confirm whether contributions made to this project are taken in under the same/outbound license, that is: Microsoft Public License (MS-PL)?

As a side note, it looks like all your source files have "all rights reserved" with no indication of the license that applies, you might want to add a notice in the source files MS-PL applies (best practice, a la ASF and FSF projects).  :)

Thanks!

**Comment by wm1** [comment]
There is a LICENSE file.
