### ISSUE TITLE
usbview Nullpointer Exception in XML Export

### ISSUE THREAD

**Issue by sevenity** [Microsoft/Windows-driver-samples#61]
Hi,

usbview crashes during XML export, when a certain hardware (e.g. my no-name USB3 ExpressCard) is connected.

The bug is in xmlhelper.cpp, function XmlAddHostController, line 343:
`USB_CONTROLLER_FLAVOR flavor = hcInfo->ControllerInfo->ControllerFlavor;`
Problem: It is possible that hcInfo->ControllerInfo is NULL.

Therefore that line simply needs to move down into the subsequent if block:
`if(NULL != hcInfo->ControllerInfo)
{
 ...
}`

I have tested that suggestion, works fine. I just don't have time to create a branch and a Pull request.

**Comment by wm1** [comment]
Fixed in WDK version 1607
