### ISSUE TITLE
无法解析的外部符号 __stdio_common_vswprintf

### ISSUE THREAD

**Issue by CodeMan-P** [microsoft/Windows-driver-samples#630]
vs2019 16.10.
wdk 10.0.19041.685
sdk 10.0.19041.685
Windows-driver-samples -> spb -> SpbTestTool -> 无法解析的外部符号 __stdio_common_vswprintf.

**Comment by DavidTRoach** [comment]
This appears to be a problem with VS2019 v16.10. I reverted to v16.9.4 and the issue went away.

**Comment by lwl4613615** [comment]
how can i fixed this problem?

**Comment by mariobalanica** [comment]
https://stackoverflow.com/questions/67740175/unresolved-external-symbol-stdio-common-vswprintf/67745800#67745800

**Comment by lwl4613615** [comment]
_NO_CRT_STDIO_INLINE
