### ISSUE TITLE
ndislwf - SDV reports a MustFix Defect (ndisallocatememorywithtagpriority_clean)

### ISSUE THREAD

**Issue by mwuetschner** [Microsoft/Windows-driver-samples#64]
Running the Static Driver Verifier (SDV) for the filter (ndislwf) sample reports a MustFix 
defect ndisallocatememorywithtagpriority.
What is the reason for this.
![ndislwf_sdv_mustfix](https://cloud.githubusercontent.com/assets/13467316/16195076/3f0d26da-36f8-11e6-8e46-4c9200c87f48.png)

**Comment by jtippet** [comment]
Thanks for the issue report.  You can consider this non-blocking.  This was a defect in the SDV rule.  We have fixed the rule in our latest builds of SDV.  Which version of SDV are you using?
(For reference, our internal issue number is 6774031).

**Comment by mwuetschner** [comment]
I am using the latest WDK 10.0.10586.0.
So I guess Visual Studio 2015 is using the StaticDV.exe from this version which is 4.0.505.8.
Do you have an updated version?

**Comment by banesttahp1** [comment]
No I don't, can you please give me instructions on how to fix my macbook in the command Administration X .diskpart.exe,  the partition were windows is stored is locked. I don't know how to fix it.
