### ISSUE TITLE
Installing Sysvad unsuccessful | devcon failed

### ISSUE THREAD

**Issue by akashrajkn** [microsoft/Windows-driver-samples#677]
I am following the driver (build) and installation process as mentioned here: [SysVAD Virtual Audio Device Driver Sample](https://docs.microsoft.com/en-us/samples/microsoft/windows-driver-samples/sysvad-virtual-audio-device-driver-sample/)

- I am able to build the solution on VS (debug, win32 configuration)
- On running the sample on target computer (windows 11, VS2019):
    - I get the following error: `C:\\Tools\\devcon failed`

```
C:\SysvadDriver>C://Tools//devcon install ComponentizedAudioSample.inf Root\Sysvad_ComponentizedAudioSample
C://Tools//devcon failed.
```

Any help is appreciated. How can I debug this?

**Comment by shilanzhang** [comment]
I got this error due to   the package in fact is not in current dir.  for you case, are  sure all the files is under c:\sysvadDriver ?

**Comment by akashrajkn** [comment]
Thanks for the reply. I will have to check it out and let you know, since it's been a few months
