### ISSUE TITLE
[SimpleMediaSourceDriver] Driver signature is invalid

### ISSUE THREAD

**Issue by AntumArk** [microsoft/Windows-driver-samples#678]
### Problem
I have encountered a problem while trying to add built SimpleMediaSource driver. The driver builds, and all of the four files are present, but I can't seem to be able to add the device.

![image](https://user-images.githubusercontent.com/23199497/144383828-03378d8c-41be-4d3e-b906-607603491a03.png)

### Used commands
`C:\Users\[User]\Windows-driver-samples\general\SimpleMediaSource\x64\Release>pnputil /i /a SimpleMediaSourceDriver.inf
Microsoft PnP Utility

Processing inf :            SimpleMediaSourceDriver.inf
Adding the driver package failed : The third-party INF does not contain digital signature information.

Total attempted:              1
Number successfully imported: 0

C:\Users\[User]\Windows-driver-samples\general\SimpleMediaSource\x64\Release>cd SimpleMediaSourceDriver

C:\Users\[User\Windows-driver-samples\general\SimpleMediaSource\x64\Release\SimpleMediaSourceDriver>pnputil /i /a SimpleMediaSourceDriver.inf
Microsoft PnP Utility

Processing inf :            SimpleMediaSourceDriver.inf
Adding the driver package failed : A problem was encountered while attempting to add the driver to the store.

Total attempted:              1
Number successfully imported: 0`

Also opening CAT file, gives :
![image](https://user-images.githubusercontent.com/23199497/144384111-4aee5ade-2b3a-4726-b983-d771da2cf26b.png)

### Purpose for using this driver
I wish to emulate several cameras, so I could perform test on my application both locally and in CI/CI.

**Comment by rakendrathapa** [comment]
Either you need to have MS-approved certificates and sign the driver. That's a big process involved !!

Else, you need to disable signing enforcement on your test machine. 
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/test-signing

**Comment by AntumArk** [comment]
Oh, so I guess I won't be able to certificate. Indeed that would be a big process. I am currently working on a different part of a project, but I will try disabling the signing. Thanks!
