### ISSUE TITLE
Windows-driver-samples / network / trans / stmedit --  documentations is wrong.

### ISSUE THREAD

**Issue by Rohit-MSFT** [Microsoft/Windows-driver-samples#71]
Readme document's "Create Registry values section" ;;; most of the information is invalid.
Can you kindly refer to the sample's : https://github.com/Microsoft/Windows-driver-samples/blob/master/network/trans/stmedit/sys/StreamEdit.c  top section for correct values that can be put in the registry as configuration parameters.

**Comment by wm1** [comment]
Fixed on the same day: commit aa6e0b36eb93
