### ISSUE TITLE
netlwf.inf fails infverify

### ISSUE THREAD

**Issue by HollisTech** [microsoft/Windows-driver-samples#848]
The sample inf file has two problems:
1. pnplockdown is not specified in the version section.
2.  the [Common.Params.reg] section from lines 166-180 attempt to set registry parameters in, for example FilterDriverParams\DriverParam but infverify insists that these must be in the 'Parameters' key. 

These issues cause infverify to fail during the build.

Error for (2) from infverify: Validating netlwf.inf
  ERROR(1323) in C:\Users\xxxx\yyyy\ndis-filter\x64\Release\netlwf.inf, line 139: Service registry key 'ParamDesc' must be under the Parameters subkey.
  INF is NOT VALID
If the sample inf is just trying to illustrate how to set a registry value in the inf file, and 'FilterDriverParams' is irrelevant, it should be replaced with e.g. 'Parameters\FilterDriverParams' so that the build doesn't fail.

Same with (1) pnplockdown: if infverify is always going to flunk the inf file for not setting this, all the inf files ought to set it.

**Comment by jasonknichel** [comment]
Thanks for the report.  These issues with netlwf.inf should be fixed with https://github.com/microsoft/Windows-driver-samples/pull/945
