### ISSUE TITLE
Fix code scanning alert - Signed overflow check - storage/class/cdrom/src/ioctl.c

### ISSUE THREAD

**Issue by lauragonzalezzz** [microsoft/Windows-driver-samples#876]
Tracking issue for:
- [ ] https://github.com/microsoft/Windows-driver-samples/security/code-scanning/11

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by lauragonzalezzz** [comment]
Hi @bharsaklemukesh975! Thank you for catching this! This seems to be a stale issue because the cdrom driver sample has been archived from this repository and is no longer published. I'm afraid your effort would likely be wasted in terms of improving this repo (I doubt your PR would even be approved) but I wont deter you from getting your hands on some code to support your learning journey!

**Comment by bharsaklemukesh975** [comment]
Hello @lauragonzalezzz , Thanks for getting back to me so quickly and briefly. If you come across any other issues that I can work on instead of this, please give me a shout. Cheers!
