### ISSUE TITLE
nullFilter.inf : error

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/Windows-driver-samples#889]
已启动重新生成…
1>------ 已启动全部重新生成: 项目: nullFilter, 配置: Debug Win32 ------
1>Building 'nullFilter' with toolset 'WindowsKernelModeDriver10.0' and the 'Universal' target platform.
1>Stamping Debug\nullFilter.inf
1>Stamping [Version] section with DriverVer=02/22/2023,7.41.29.216
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\nullFilter\nullFilter.inf : error 1420: [DefaultInstall]-based INF cannot be processed as Primitive.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\nullFilter\nullFilter.inf(8-8): warning 1324: [Version] section should specify PnpLockdown=1 to prevent external apps from modifying installed driver files.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\nullFilter\nullFilter.inf(25-25): error 1421: Section [DefaultInstall] should have an architecture decoration.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\nullFilter\nullFilter.inf(36-36): error 1421: Section [DefaultUninstall] should have an architecture decoration.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\nullFilter\nullFilter.inf(71-71): warning 1205: Section [NullFilter.DriverFiles] referenced from DelFiles and CopyFiles directive.
1>已完成生成项目“nullFilter.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by jasonknichel** [comment]
Thank you for the report. These are known issues that should not appear if you build the sample with the Build-Sample.ps1 script at the root of the repo.
