### ISSUE TITLE
cannot open port settings of HyperTerminal Using WDFSerial driver sample under windows xp

### ISSUE THREAD

**Issue by Mapleaph** [Microsoft/Windows-driver-samples#89]
I am new to windows device driver development, I have a PCI bus device and I want to test the windows wdfserial.sys device driver on the device under windows XP, the communication is OK, but I just find that, when I'm using the system supplied HyperTerminal.exe to set the properties of a COM port, there is no pop-up window of port settings tab when I click the settings button, Any idea?

**Comment by AlexeiFedorov** [comment]
Does “mode COMx” command work for you?

**Comment by Mapleaph** [comment]
Thanks for your reply @AlexeiFedorov , the command you formerly mentioned does work for me, but I think I found where the problem is. I just pulled a request to submit my modification of the source code.

**Comment by wm1** [comment]
Merge pull request #93 - Fix NULL-terminating device name when writing to DEVICEMAP/SERIALCOMM
