### ISSUE TITLE
cancelSafe.inf : warning

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/Windows-driver-samples#891]
已启动重新生成…
1>------ 已启动全部重新生成: 项目: cancelSafe, 配置: Debug x64 ------
1>Building 'cancelSafe' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>Stamping x64\Debug\cancelSafe.inf
1>Stamping [Version] section with DriverVer=02/22/2023,7.43.46.533
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\cancelSafe\cancelSafe.inf : warning 1420: [DefaultInstall]-based INF cannot be processed as Primitive.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\cancelSafe\cancelSafe.inf(8-8): warning 1324: [Version] section should specify PnpLockdown=1 to prevent external apps from modifying installed driver files.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\cancelSafe\cancelSafe.inf(25-25): warning 1421: Section [DefaultInstall] should have an architecture decoration.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\cancelSafe\cancelSafe.inf(36-36): warning 1421: Section [DefaultUninstall] should have an architecture decoration.
1>D:\code\microsoft\Windows-driver-samples\filesys\miniFilter\cancelSafe\cancelSafe.inf(74-74): warning 1205: Section [MiniFilter.DriverFiles] referenced from DelFiles and CopyFiles directive.

**Comment by jasonknichel** [comment]
Thank you for the report. These are known issues that should not appear if you build the sample with the Build-Sample.ps1 script at the root of the repo.
