### ISSUE TITLE
Update 'microsoft/setup-msbuild'

### ISSUE THREAD

**Issue by wm1** [microsoft/Windows-driver-samples#916]
Every PR reports the following warnings. For example:
https://github.com/microsoft/Windows-driver-samples/actions/runs/4327863236

2 warnings:
 - Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: `microsoft/setup-msbuild@v1.0.2`.
 - The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

Search 'https://github.com/microsoft/Windows-driver-samples/search?q=setup-msbuild' and there are 4 hits. For example:
```
.github/workflows/ci.yml
        uses: microsoft/setup-msbuild@v1.0.2
```
Look at [setup-msbuild release](https://github.com/microsoft/setup-msbuild/releases), v1.1.2 updates to node16, v1.1.3 fixes the set-output issue.

**Comment by NeoAdonis** [comment]
Resolved!
