### ISSUE TITLE
some question about WSK

### ISSUE THREAD

**Issue by Iamgublin** [Microsoft/Windows-driver-samples#95]
unresolved symbol  NPI_WSK_INTERFACE_ID,How to define this variable？

**Comment by wm1** [comment]
network\wsk\echosrv should build clean without any modification.

The said symbol is imported from uuid.lib.
```
      Searching .. Windows Kits\10\lib\10.0.14393.0\um\x64\\uuid.lib:
        Found NPI_WSK_INTERFACE_ID
          Referenced in wsksmple.obj
```
