### ISSUE TITLE
git directory name case problems

### ISSUE THREAD

**Issue by SamB** [Microsoft/Windows-driver-samples#96]
You have several groups of directories in your tree with names that differ only in case. Since you're coming from Windows, each such group is presumably meant to be just one directory.

For example, you have:
  * `AVStream` and `avstream`
  * `SPB` and `spb`
  * `Sensors` and `sensors`

(For all I know, those are actually the only cases, but I didn't look very hard for additional instances of the problem.)

Even if you don't care about users with case-sensitive filesystems, 
  1. This affects navigating the tree on github, and probably in many other tools
  2. It can also lead to merge conflicts 

I found [an SO question](http://stackoverflow.com/questions/13828066/how-do-i-solve-a-folder-capitalization-conflict-with-git-on-windows) about how to fix that], which lead me to a [blog post](http://www.woodcp.com/2013/01/git-unite-fix-case-sensitive-file-paths-on-windows/) about [Git Unite](https://github.com/tawman/git-unite), a tool created to simplify cleaning up after such problems.

**Comment by wm1** [comment]
pull request #124 is merged.
