### ISSUE TITLE
Binaries- Documentation on Build

### ISSUE THREAD

**Issue by Srikanthkumarreddyyekollu** [Microsoft/Windows-driver-samples#97]
Can I get binaries of the driver or Steps on how to build and create binaries to use please.

**Comment by yubaochina** [comment]
You can refer to: https://msdn.microsoft.com/library/windows/hardware/hh439659(v=vs.85).aspx

Thanks,

**Comment by Srikanthkumarreddyyekollu** [comment]
Thank you Yubaolio.
