### ISSUE TITLE
APOs HKCR\CLSID: Registry script or INF AddReg?

### ISSUE THREAD

**Issue by thxkiwi** [microsoft/Windows-driver-samples#980]
The audio/sysvad example code has APOs using rgs files for adding CLSIDs but the INFs also add the same CLSIDs. I've actually never seen the CLSIDs removed so I'm wondering are the registry scripts actually utilized? 

What is the recommended "best practice" for registering the APO HKCR\CLSIDs; registry scripts or INF AddReg?

**Comment by kkotte** [comment]
The recommended way to register APOs is using INF AddReg
